export const PORTFOLIO_ITEMS = [
  {
    index: 0,
    slug: "matma",
    date: "2015",
    color: "#15a34a",
    imageSize: { height: 200, width: 100 },
    windowsStoreLink:
      "https://www.microsoft.com/pl-pl/p/matma/9nblggh6hs3l?activetab=pivot:overviewtab",
    screenshotsCount: 3,
    screenshotSize: { height: 580, width: 320 },
    casesCount: 0,
  },
  {
    index: 1,
    slug: "logicos",
    date: "2016-2017",
    color: "#0a91b2",
    imageSize: { height: 200, width: 100 },
    windowsStoreLink:
      "https://www.microsoft.com/en-us/p/logicos/9nblggh51blc?rtc=1&activetab=pivot:overviewtab",
    screenshotsCount: 3,
    screenshotSize: { height: 580, width: 320 },
    casesCount: 0,
  },
  {
    index: 2,
    slug: "whats-inside",
    date: "2017",
    color: "#5a6778",
    imageSize: { height: 200, width: 100 },
    screenshotsCount: 2,
    screenshotSize: { height: 580, width: 320 },
    casesCount: 0,
  },
  {
    index: 3,
    slug: "qopml",
    date: "2019-2020",
    color: "#e39922",
    imageSize: { height: 200, width: 330 },
    screenshotsCount: 2,
    screenshotSize: { height: 517, width: 1024 },
    casesCount: 0,
  },
  {
    index: 4,
    slug: "simple-weather-app",
    date: "2021",
    color: "#2463eb",
    imageSize: { height: 200, width: 100 },
    githubLink: "https://github.com/lukaszkurantdev/weather-app",
    screenshotsCount: 3,
    screenshotSize: { height: 693, width: 320 },
    casesCount: 0,
  },
  {
    index: 5,
    slug: "dzielo-biblijne",
    date: "2021",
    color: "#b43342",
    imageSize: { height: 200, width: 100 },
    screenshotsCount: 3,
    screenshotSize: { height: 693, width: 320 },
    casesCount: 3,
    googlePlayLink:
      "https://play.google.com/store/apps/details?id=com.dzielobiblijne&hl=pl&gl=US",
    appStoreLink:
      "https://apps.apple.com/pl/app/dzie%C5%82o-biblijne/id1595265008?l=pl",
  },
  {
    index: 6,
    slug: "constcash",
    date: "2021-2023",
    color: "#e39922",
    imageSize: { height: 200, width: 100 },
    screenshotsCount: 3,
    screenshotSize: { height: 693, width: 320 },
    casesCount: 4,
    appStoreLink:
      "https://apps.apple.com/app/apple-store/id1586637609?pt=123524905&ct=lkwebpage&mt=8",
  },
  {
    index: 7,
    slug: "constcash-web",
    date: "2022",
    color: "#e39922",
    imageSize: { height: 200, width: 330 },
    screenshotsCount: 0,
    screenshotSize: { height: 580, width: 320 },
    casesCount: 0,
    websiteLink: "https://constcash.com/",
  },
  {
    index: 8,
    slug: "plant-you-grow",
    date: "2022-2023",
    color: "#7ba25e",
    imageSize: { height: 200, width: 330 },
    screenshotsCount: 0,
    screenshotSize: { height: 580, width: 320 },
    casesCount: 0,
    websiteLink: "https://dogtronic.io/case-studies/plant-you-grow/",
  },
  {
    index: 9,
    slug: "portfolio-page",
    date: "2023",
    color: "#2463eb",
    imageSize: { height: 200, width: 330 },
    screenshotsCount: 0,
    screenshotSize: { height: 580, width: 320 },
    casesCount: 0,
    githubLink: "TODO",
  },
].reverse();
