import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { appWithTranslation } from "next-i18next";
import Head from "next/head";
import classNames from "classnames";

import styles from "./styles.module.css";

import { Lato } from "@next/font/google";
import { Navbar } from "@/modules/layout/Navbar/NavBar";
import { Footer } from "@/modules/layout/Footer/Footer";

const latoFont = Lato({ subsets: ["latin"], weight: ["400", "700"] });

const MyApp = ({ Component, pageProps }: AppProps) => (
  <>
    <Head>
      {/* TO DO */}
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={classNames(styles.main, latoFont.className)}>
      <Navbar />
      <Component {...pageProps} />
      <Footer />
    </main>
  </>
);

export default appWithTranslation(MyApp);
